### ISSUE TITLE
Add a GitHub-based comment system integration

### ISSUE THREAD

**Issue by imgios** [imgios/not-much#33]
It would be good to have a GitHub based commenting system integrated into the theme. This would allow the owner to have comments in their blog.

I think a good choice would be [Giscus](https://giscus.app) powered by GitHub Discussions, which allows comments and reactions.

The integration could be done by adding the commenting system parameters in the site config file, and with a parameter in the page header, this way the user can decide whether or not to add the comments.

e.g.,

<kbd>config.toml</kbd>
```toml
[params.giscus]
enable = true # or false
repository = "string"
theme = "string"
# other mandatory parameters
...
```

<kbd>/content/posts/hello-world.md</kbd>
```markdown
---
comments: true # or false
---

Hello, world!
```
